# global settings
global:
  scrape_interval:     12s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 12s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

alerting:
  alertmanagers:
    - static_configs:
      - targets: ["alertmanager:9093"]

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - /etc/prometheus/alert_rules.yml
    #- /srv/prom-alert/alert_rules.yml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']


  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: 'blackbox-HealthCheck'
    # scheme: http
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets: #in order to minitor healthcheck of different APIs, you can put their APIs here. Blackbox will gather them.
        - https://api.test.com/finance2/status
        - https://api.test.com/accounts/status?service_name=postgres
        - http://0.0.0.0:8080     # fake local web service.
        - https://google.com

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'asset-nodeexporter'
    static_configs:
    - targets:
      - node-exporter:9100
    relabel_configs:
      - source_labels: [__address__]
        regex: '.*'
        target_label: instance
        replacement: 'Asset'

  - job_name: 'stage-nodeexporter'
    static_configs:
    - targets:
      - x.x.x.x:2021
    relabel_configs:
      - source_labels: [__address__]
        regex: '.*'
        target_label: instance
        replacement: 'Stage'

  - job_name: 'production-nodeexporter'
    static_configs:
    - targets:
      - x.x.x.x:2021
    relabel_configs:
      - source_labels: [__address__]
        regex: '.*'
        target_label: instance
        replacement: 'Production'
